import logging
import pprint
from constants import causes, csrs, csrs32
from shared_utils import InstrDict

pp = pprint.PrettyPrinter(indent=4)
logging.basicConfig(level=logging.INFO, format="%(levelname)s:: %(message)s")

def make_rust(instr_dict: InstrDict):
    mask_match_str = ""
    mask_match_str_32 = ""
    mask_match_str_64 = ""
    for i in instr_dict:
        name = i.replace("_", ".")
        variables : list[str] = []
        for v in instr_dict[i]["variable_fields"]:
            variables.extend(canonicalize_arg(v))
        if "32" in instr_dict[i]["extension"][0]:
            mask_match_str_32 += f'    Spec::new("{name}", {instr_dict[i]["mask"]}, {instr_dict[i]["match"]}, vec![{", ".join(variables)}]),\n'
        elif "64" in instr_dict[i]["extension"][0]:
            mask_match_str_64 += f'    Spec::new("{name}", {instr_dict[i]["mask"]}, {instr_dict[i]["match"]}, vec![{", ".join(variables)}]),\n'
        else:
            mask_match_str += f'    Spec::new("{name}", {instr_dict[i]["mask"]}, {instr_dict[i]["match"]}, vec![{", ".join(variables)}]),\n'
    with open("isa.rs", "w", encoding="utf-8") as rust_file:
        rust_file.write(
            f"""/* Automatically generated by parse_opcodes */
use once_cell::sync::Lazy;
use crate::args::*;

#[derive(Debug, Clone)]
pub struct Spec {{
  pub name: String,
  pub mask_bits: u32,
  pub match_bits: u32,
  pub args: Vec<fn(u32)->(Arg, String)>,
}}

impl Spec {{    
    pub fn new(name: &str, mask_bits: u32, match_bits: u32, args: Vec<fn(u32)->(Arg, String)>) -> Self {{
        Self {{ name: name.to_string(), mask_bits, match_bits, args }}
    }}

    pub fn compare(&self, code: u32) -> bool {{
        (code & self.mask_bits) == self.match_bits
    }}
}}

pub static RV_ISA_SPECS_REGULAR: Lazy<Vec<Spec>> = Lazy::new(|| vec![
{mask_match_str}]);

pub static RV_ISA_SPECS_32: Lazy<Vec<Spec>> = Lazy::new(|| vec![
{mask_match_str_32}]);

pub static RV_ISA_SPECS_64: Lazy<Vec<Spec>> = Lazy::new(|| vec![
{mask_match_str_64}]);

"""
        )

    const_str = ""
    for num, name in csrs + csrs32:
        const_str += f"const CSR_{name.upper()}: u16 = {hex(num)};\n"
    for num, name in causes:
        const_str += (
            f'const CAUSE_{name.upper().replace(" ","_")}: u8 = {hex(num)};\n'
        )
    with open("isa_consts.rs", "w", encoding="utf-8") as rust_file:
        rust_file.write(
            f"""/* Automatically generated by parse_opcodes */
{const_str}
"""
        )

# helper function to split shared arguments
def canonicalize_arg(v: str) -> list[str]:
    if v == "rd_rs1_p":
        return ["rd_p", "rs1_p"]
    elif v == "rd_rs1_n0":
        return ["rd_n0", "rs1_n0"]
    else:
        return [v]

