import logging
import pprint

from constants import causes, csrs, csrs32
from shared_utils import InstrDict

pp = pprint.PrettyPrinter(indent=4)
logging.basicConfig(level=logging.INFO, format="%(levelname)s:: %(message)s")


def make_rust(instr_dict: InstrDict):
    mask_match_str = ""
    for i in instr_dict:
        mask_match_str += f'    specs.insert("{i}", Spec::new({instr_dict[i]["mask"]}, {instr_dict[i]["match"]}, vec![{", ".join(instr_dict[i]["variable_fields"])}]));\n'
    # for num, name in csrs + csrs32:
    #     mask_match_str += f"const CSR_{name.upper()}: u16 = {hex(num)};\n"
    # for num, name in causes:
    #     mask_match_str += (
    #         f'const CAUSE_{name.upper().replace(" ","_")}: u8 = {hex(num)};\n'
    #     )
    with open("isa.rs", "w", encoding="utf-8") as rust_file:
        rust_file.write(
            f"""/* Automatically generated by parse_opcodes */
use std::collections::HashMap;
use once_cell::sync::Lazy;
use crate::insn::{{RawInsn, Arg}};

pub struct Spec {{
    mask_bits: u32,
    match_bits: u32,
    args: Vec<fn(&RawInsn)->Arg>,
}}

impl Spec {{
    pub fn new(mask_bits: u32, match_bits: u32, args: Vec<fn(&RawInsn)->Arg>) -> Self {{
        Self {{ mask_bits, match_bits, args }}
    }}
}}

pub static RV_ISA_SPECS: Lazy<HashMap<&'static str, Spec>> = Lazy::new(|| {{
    let mut specs = HashMap::new();
{mask_match_str}    specs
}});
""")

    const_str = ""
    for num, name in csrs + csrs32:
        const_str += f"const CSR_{name.upper()}: u16 = {hex(num)};\n"
    for num, name in causes:
        const_str += (
            f'const CAUSE_{name.upper().replace(" ","_")}: u8 = {hex(num)};\n'
        )
    with open("isa_consts.rs", "w", encoding="utf-8") as rust_file:
        rust_file.write(
            f"""/* Automatically generated by parse_opcodes */
{const_str}
"""
        )







